version: '3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:10.2.3-ce.0'
    restart: always
    hostname: '${GITLAB_HOSTNAME}'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${GITLAB_URL}'
        nginx['redirect_http_to_https']=true
        registry_external_url '${GITLAB_REGISTRY_URL}'
        pages_external_url '${GITLAB_PAGES_URL}'
        pages_nginx['redirect_http_to_https']=true
        gitlab_rails['registry_enabled']=true
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '443:443'
      - '80:80'
      - '2222:22'
      - '5000:4567'
    volumes:
      - 'gitlab-config:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'
    networks:
      - gitlab-network
    deploy:
      placement:
        constraints: [node.role == manager]

  runner:
    image: 'gitlab/gitlab-runner:alpine'
    volumes:
      - 'gitlab-runner-config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - DOCKER_NETWORK_MODE=gitlab-ci_gitlab-network
    networks:
      - gitlab-network
    deploy:
      mode: global
      placement:
        constraints: [node.role == worker]

volumes:
  gitlab-config:
  gitlab-runner-config:
  gitlab-logs:
  gitlab-data:

networks:
  gitlab-network:
