version: '3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:10.2.3-ce.0'
    restart: always
    hostname: '${GITLAB_HOSTNAME}'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${GITLAB_URL}'
        registry_external_url '${GITLAB_REGISTRY_URL}'
        pages_external_url '${GITLAB_PAGES_URL}'
        nginx['listen_port']=80
        nginx['listen_https']=false
        nginx['proxy_set_headers']={"X-Forwarded-Proto"=>"https","X-Forwarded-Ssl"=>"on"}
        gitlab_rails['initial_shared_runners_registration_token']="${GITLAB_RUNNER_TOKEN}"
        gitlab_rails['registry_enabled']=true
        registry_nginx['listen_port']=80
        registry_nginx['listen_https']=false
        registry_nginx['proxy_set_headers']={"X-Forwarded-Proto"=>"https","X-Forwarded-Ssl"=>"on"}
        pages_nginx['listen_port']=80
        pages_nginx['listen_https']=false
        pages_nginx['proxy_set_headers']={"X-Forwarded-Proto"=>"https","X-Forwarded-Ssl"=>"on"}
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
    volumes:
      - 'gitlab-config:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'
    networks:
      - gitlab-network
    deploy:
      placement:
        constraints: [node.role == manager]

  runner:
    image: 'gitlab/gitlab-runner:alpine'
    volumes:
      - 'gitlab-runner-config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - RUNNER_TAG_LIST=docker,runner
      - REGISTER_RUN_UNTAGGED=true
      - REGISTER_LOCKED=false
      - CI_SERVER_URL=${GITLAB_URL}
      - REGISTRATION_TOKEN=${GITLAB_RUNNER_TOKEN}
      - RUNNER_OUTPUT_LIMIT=20480
      - RUNNER_EXECUTOR=docker
      #- DOCKER_NETWORK_MODE=gitlab-ci_gitlab-network
      - DOCKER_VOLUMES=/var/run/docker.sock:/var/run/docker.sock
      - DOCKER_PRIVILEGED=true
      - DOCKER_IMAGE=alpine:latest
    networks:
      - gitlab-network

volumes:
  gitlab-config:
  gitlab-runner-config:
  gitlab-logs:
  gitlab-data:

networks:
  gitlab-network:
